// Generated by oadio-reprice-radio.mjs — do not edit by hand.
// LIVE mode. SKU -> { price, mode }.
export const TAX_RATE = "txr_1TjBUsAlhJDHJxnO7GZm5MSh";

export const SKUS = {
  "radio_starter": {
    "price": "price_1TjBtdAlhJDHJxnOzXAEW1cv",
    "mode": "subscription"
  },
  "radio_starter_yr": {
    "price": "price_1TjBteAlhJDHJxnORGSRptnA",
    "mode": "subscription"
  },
  "radio_pro": {
    "price": "price_1TjBtfAlhJDHJxnOUh3lQ4S5",
    "mode": "subscription"
  },
  "radio_pro_yr": {
    "price": "price_1TjBtfAlhJDHJxnOx9OUzOhk",
    "mode": "subscription"
  },
  "radio_broadcaster": {
    "price": "price_1TjBtgAlhJDHJxnOzAhiX85i",
    "mode": "subscription"
  },
  "radio_broadcaster_yr": {
    "price": "price_1TjBthAlhJDHJxnOYwAicDGh",
    "mode": "subscription"
  },
  "webdesign_landing": {
    "price": "price_1TjBUwAlhJDHJxnO6Hv1dUVt",
    "mode": "payment"
  },
  "webdesign_business": {
    "price": "price_1TjBUwAlhJDHJxnO43BGGWZH",
    "mode": "payment"
  },
  "consulting_day": {
    "price": "price_1TjBUxAlhJDHJxnOqVFCepbj",
    "mode": "payment"
  },
  "consulting_retainer": {
    "price": "price_1TjBUxAlhJDHJxnOW87tAZyg",
    "mode": "subscription"
  },
  "consulting_retainer_yr": {
    "price": "price_1TjBUyAlhJDHJxnOEC7vzpRT",
    "mode": "subscription"
  }
};
